# Домашняя работа 01: NumPy основы
## Примеры работы с NumPy

### 1. Импорт библиотеки

In [1]:
import numpy as np
import matplotlib.pyplot as plt

### 2. Создание массивов

In [2]:
# Создание массива из списка
arr1 = np.array([1, 2, 3, 4, 5])
print("Массив из списка:", arr1)

# Двумерный массив
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\nДвумерный массив:")
print(arr2d)

# Массив нулей
zeros = np.zeros((3, 4))
print("\nМассив нулей:")
print(zeros)

# Массив единиц
ones = np.ones((2, 3))
print("\nМассив единиц:")
print(ones)

# Массив с последовательностью
range_arr = np.arange(0, 10, 2)
print("\nПоследовательность:", range_arr)

# Линейное пространство
lin_arr = np.linspace(0, 1, 5)
print("\nЛинейное пространство:", lin_arr)

Массив из списка: [1 2 3 4 5]

Двумерный массив:
[[1 2 3]
 [4 5 6]]

Массив нулей:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Массив единиц:
[[1. 1. 1.]
 [1. 1. 1.]]

Последовательность: [0 2 4 6 8]

Линейное пространство: [0.   0.25 0.5  0.75 1.  ]


### 3. Shape и dtype

In [3]:
# Создаем различные массивы
arr_int = np.array([1, 2, 3])
arr_float = np.array([1.0, 2.0, 3.0])
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])

print("Массив целых чисел:")
print("Значения:", arr_int)
print("Shape:", arr_int.shape)
print("dtype:", arr_int.dtype)

print("\nМассив дробных чисел:")
print("Значения:", arr_float)
print("Shape:", arr_float.shape)
print("dtype:", arr_float.dtype)

print("\nДвумерный массив:")
print("Значения:")
print(arr_2d)
print("Shape:", arr_2d.shape)
print("dtype:", arr_2d.dtype)
print("Размерность:", arr_2d.ndim)
print("Количество элементов:", arr_2d.size)

Массив целых чисел:
Значения: [1 2 3]
Shape: (3,)
dtype: int64

Массив дробных чисел:
Значения: [1. 2. 3.]
Shape: (3,)
dtype: float64

Двумерный массив:
Значения:
[[1 2]
 [3 4]
 [5 6]]
Shape: (3, 2)
dtype: int64
Размерность: 2
Количество элементов: 6


### 4. Индексирование и срезы

In [4]:
# Создаем массив
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print("Исходный массив:", arr)

# Базовое индексирование
print("\nБазовое индексирование:")
print("arr[0] =", arr[0])      # Первый элемент
print("arr[-1] =", arr[-1])    # Последний элемент

# Срезы
print("\nСрезы:")
print("arr[1:4] =", arr[1:4])        # Элементы с 1 по 3
print("arr[:3] =", arr[:3])          # Первые 3 элемента
print("arr[3:] =", arr[3:])          # С 3 элемента до конца
print("arr[::2] =", arr[::2])        # Каждый второй элемент

# Двумерный массив
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nДвумерный массив:")
print(arr_2d)
print("\nИндексирование 2D:")
print("arr_2d[0, 1] =", arr_2d[0, 1])    # Элемент в строке 0, столбец 1
print("arr_2d[1] =", arr_2d[1])          # Вторая строка
print("arr_2d[:, 1] =", arr_2d[:, 1])    # Второй столбец
print("arr_2d[0:2, 1:3]:")
print(arr_2d[0:2, 1:3])

Исходный массив: [10 20 30 40 50 60 70]

Базовое индексирование:
arr[0] = 10
arr[-1] = 70

Срезы:
arr[1:4] = [20 30 40]
arr[:3] = [10 20 30]
arr[3:] = [40 50 60 70]
arr[::2] = [10 30 50 70]

Двумерный массив:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Индексирование 2D:
arr_2d[0, 1] = 2
arr_2d[1] = [4 5 6]
arr_2d[:, 1] = [2 5 8]
arr_2d[0:2, 1:3]:
[[2 3]
 [5 6]]


### 5. Простые операции

In [5]:
# Арифметические операции
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Массив a:", a)
print("Массив b:", b)
print("\nАрифметические операции:")
print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)
print("b / a =", b / a)
print("a ** 2 =", a ** 2)

# Операции с скалярами
print("\nОперации со скалярами:")
print("a + 10 =", a + 10)
print("a * 2 =", a * 2)

# Матричные операции
matrix = np.array([[1, 2], [3, 4]])
print("\nМатричные операции:")
print("Матрица:")
print(matrix)
print("Транспонирование:")
print(matrix.T)
print("Умножение матриц:")
print(np.dot(matrix, matrix))

# Логические операции
print("\nЛогические операции:")
print("a > 2 =", a > 2)
print("a == b =", a == b)
print("Элементы a больше 1:", a[a > 1])

Массив a: [1 2 3]
Массив b: [4 5 6]

Арифметические операции:
a + b = [5 7 9]
a - b = [-3 -3 -3]
a * b = [ 4 10 18]
b / a = [4.  2.5 2. ]
a ** 2 = [1 4 9]

Операции со скалярами:
a + 10 = [11 12 13]
a * 2 = [2 4 6]

Матричные операции:
Матрица:
[[1 2]
 [3 4]]
Транспонирование:
[[1 3]
 [2 4]]
Умножение матриц:
[[ 7 10]
 [15 22]]

Логические операции:
a > 2 = [False False  True]
a == b = [False False False]
Элементы a больше 1: [2 3]


### 6. Статистики

In [6]:
# Создаем массив для статистик
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Данные:", data)

# Базовые статистики
print("\nБазовые статистики:")
print("Сумма:", np.sum(data))
print("Среднее:", np.mean(data))
print("Медиана:", np.median(data))
print("Стандартное отклонение:", np.std(data))
print("Дисперсия:", np.var(data))
print("Минимум:", np.min(data))
print("Максимум:", np.max(data))

# Статистики по осям
data_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nДвумерные данные:")
print(data_2d)
print("\nСтатистики по осям:")
print("Сумма по столбцам:", np.sum(data_2d, axis=0))
print("Сумма по строкам:", np.sum(data_2d, axis=1))
print("Среднее по столбцам:", np.mean(data_2d, axis=0))
print("Максимум по строкам:", np.max(data_2d, axis=1))

Данные: [ 1  2  3  4  5  6  7  8  9 10]

Базовые статистики:
Сумма: 55
Среднее: 5.5
Медиана: 5.5
Стандартное отклонение: 2.8722813232690143
Дисперсия: 8.25
Минимум: 1
Максимум: 10

Двумерные данные:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Статистики по осям:
Сумма по столбцам: [12 15 18]
Сумма по строкам: [ 6 15 24]
Среднее по столбцам: [4. 5. 6.]
Максимум по строкам: [3 6 9]


### 7. Дополнительные примеры

In [7]:
# Изменение формы массива
arr = np.arange(12)
print("Исходный массив:", arr)
reshaped = arr.reshape(3, 4)
print("\nПосле reshape(3, 4):")
print(reshaped)

# Конкатенация
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
concat = np.concatenate([a, b])
print("\nКонкатенация:", concat)

# Уникальные элементы
arr_with_duplicates = np.array([1, 2, 2, 3, 4, 4, 4, 5])
unique = np.unique(arr_with_duplicates)
print("\nУникальные элементы:", unique)

Исходный массив: [ 0  1  2  3  4  5  6  7  8  9 10 11]

После reshape(3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Конкатенация: [1 2 3 4 5 6]

Уникальные элементы: [1 2 3 4 5]
